package CalcApp;


/**
* CalcApp/CalcOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./Calc.idl
* jueves 2 de marzo de 2023 21H32' CET
*/

public interface CalcOperations 
{
  float sum (float a, float b);
  float div (float a, float b) throws CalcApp.CalcPackage.DivisionByZero;
  float mul (float a, float b);
  float sub (float a, float b);
  CalcApp.Frac addFrac (CalcApp.Frac f1, CalcApp.Frac f2);
  CalcApp.Frac subFrac (CalcApp.Frac f1, CalcApp.Frac f2);
  CalcApp.Frac mulFrac (CalcApp.Frac f1, CalcApp.Frac f2);
  CalcApp.Frac divFrac (CalcApp.Frac f1, CalcApp.Frac f2) throws CalcApp.CalcPackage.DivisionByZero;
} // interface CalcOperations
